### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by swapplays31** [rizinorg/rz-ghidra#111]
<!does this works for termux app based r2..if yes please provide solution to this>
**issue=build error on make command
make command produces the errors when building from source or using r2pm installation

**How to reproduce? = use r2pm or build from source produces errors on make command**

**Possible fix=not sure**

**Screenshots=
![Screenshot_20200530_112639](https://user-images.githubusercontent.com/61490060/83320986-1887af80-a26a-11ea-9a38-7ee68c22aabc.jpg)
![Uploading  

> #Screenshot_20200530_112656.jpg…]()
![Screenshot_20200530_112639](https://user-images.githubusercontent.com/61490060/83321000-32c18d80-a26a-11ea-8527-4c023e2b9fcc.jpg)
![Screenshot_20200530_112653](https://user-images.githubusercontent.com/61490060/83321002-33f2ba80-a26a-11ea-9d5f-c65acbdffde1.jpg)

**Comment by swapplays31** [comment]
#
[log.txt](https://github.com/radareorg/r2ghidra-dec/files/4705166/log.txt)

**Comment by XVilka** [comment]
I am closing this since the build was fixed for ARM, feel free to open a new issue if it still happens.
