### ISSUE TITLE
flags not taken into account in the disasm

### ISSUE THREAD

**Issue by radare** [rizinorg/rz-ghidra#16]
![IMAGE 2019-08-21 11:20:14](https://user-images.githubusercontent.com/917142/63419761-a5f9c180-c405-11e9-9191-e27683a466f8.jpg)

**Comment by thestr4ng3r** [comment]
ping

**Comment by XVilka** [comment]
Closing since there is no way to reproduce and it's unclear what is the reason of the problem.
