### ISSUE TITLE
ghidra can‘t match Tricore to a sleigh arch

### ISSUE THREAD

**Issue by dudamao** [rizinorg/rz-ghidra#199]
**Environment information**

Operating System: Windows 10
Cutter version: Cutter-v1.12.0 offical released
File format: elf

**Describe the bug**

I have a large elf for TC29x(around 30 MB for a single application), and I used cutter to load it.
It seems that cutter recongized the arch and disassembled rightly, but no Xref and Call were found.(Maybe it's not OK)

When I tried to recompile a function, Ghidra noted me that:

Ghidra Decompiler Error: Could not match asm.arch tricore to sleigh arch.
this bug is similar to #39 

should I use some manual setting to tell ghidra the arch?

**Comment by dudamao** [comment]
> **Environment information**
> 
> Operating System: Windows 10
> Cutter version: Cutter-v1.12.0 offical released
> File format: elf
> 
> **Describe the bug**
> 
> I have a large elf for TC29x(around 30 MB for a single application), and I used cutter to load it.
> It seems that cutter recongized the arch and disassembled rightly, but no Xref and Call were found.(Maybe it's not OK)
> 
> When I tried to recompile a function, Ghidra noted me that:
> 
> Ghidra Decompiler Error: Could not match asm.arch tricore to sleigh arch.
> this bug is similar to #39
> 
> should I use some manual setting to tell ghidra the arch?

I have used original Ghidra for this ELF and I can make sure that it worked, but original Ghidra have some disassemble issue so I want to try r2 + ghidra.

thanks for your help.

**Comment by trufae** [comment]
If you are willing to use r2+ghidra, see the https://github.com/radareorg/r2ghidra repository instead. tricore is already supported there. Also you may want to build r2 and r2ghidra from git instead of using the one shipped in the old cutter release.

**Comment by thestr4ng3r** [comment]
You can see all supported languages by rz-ghidra by using the `pdgs` command in the console. I think the one you want is probably `tricore:LE:32:tc29x` so you can choose it by calling `e ghidra.lang=tricore:LE:32:tc29x`.

Keep in mind though that the Cutter release 1.12 is already quite old and the variable is called `r2ghidra.lang` there. I am also not sure if tricore was already bundled there. But a new release is coming soon too and you can also build Cutter/Rizin/rz-ghidra from source to have it.

**Comment by dudamao** [comment]
> You can see all supported languages by rz-ghidra by using the `pdgs` command in the console. I think the one you want is probably `tricore:LE:32:tc29x` so you can choose it by calling `e ghidra.lang=tricore:LE:32:tc29x`.
> 
> Keep in mind though that the Cutter release 1.12 is already quite old and the variable is called `r2ghidra.lang` there. I am also not sure if tricore was already bundled there. But a new release is coming soon too and you can also build Cutter/Rizin/rz-ghidra from source to have it.

I really appreciate your reply! It seems rz-ghidra is working in commandline.
Latest radare2(V5.1.0) still has trouble in disassembling tricore elf(wrong address jump), maybe I should wait for a future version which can solve this problem.
