### ISSUE TITLE
Create release tarball

### ISSUE THREAD

**Issue by dmknght** [rizinorg/rz-ghidra#219]
I'm working on making rz-ghidra plugin for Parrot Sec (a prebuild that supports both rizin and rizin-cutter) and Debian standard requires tarball files from source (and it will be easier for maintainers when release files have the submodules). So it would be nice if dev team can create tags with release tarball :D

**Comment by thestr4ng3r** [comment]
Sure, should be no problem.

**Comment by dmknght** [comment]
@thestr4ng3r is there any way the release file contains submodule as well? Debian packaging downloads the release file for latest version and because of submodule, creating new debian package is impossible.

**Comment by thestr4ng3r** [comment]
Yes.

**Comment by thestr4ng3r** [comment]
0.2.0 tarball: https://github.com/rizinorg/rz-ghidra/releases/tag/v0.2.0

**Comment by dmknght** [comment]
> 0.2.0 tarball: https://github.com/rizinorg/rz-ghidra/releases/tag/v0.2.0

Thank you very much. I used debian automation tool to update latest version and it is working :D
