### ISSUE TITLE
String literals are not always shown in decompiled function calls

### ISSUE THREAD

**Issue by vysnet** [rizinorg/rz-ghidra#36]
Sometimes a function that accepts a string as an argument is decompiled with the string's address in place of the literal. This can be annoying when working on large projects.

I attached a simple vuln that demonstrates the problem (the binary is non-malicious and is attached below).

Steps to reproduce:
- `r2 -A vuln`
- `s sym.remove_fighter; pdg`
- the first call to `sym.print_opt` is decompiled  as `sym.print_opt(0x401d30, 0x50);` but should be preferably `sym.print_opt("Who do you want to remove from the competition?", 0x50);`. The disassembly view correctly detects that 0x401d30 is an address of a string literal.

My guess is that all function calls with more than 1 argument are not correctly decompiled. So far I have observed that all 1-argument function calls such as `puts(str)` and `printf(str)` have their string literals correctly shown in the decompiled code. 

[vuln.tar.gz](https://github.com/radareorg/r2ghidra-dec/files/3592587/vuln.tar.gz)

**Comment by wargio** [comment]
just to know, have you tried to do `Cs @ 0x401d30`

**Comment by XVilka** [comment]
Retested with the latest Rizin & Rz-ghidra (https://github.com/rizinorg/rizin/commit/ead601655cb8ba3655be278426ad8d6e60382227 and https://github.com/rizinorg/rz-ghidra/commit/0c9ab921afa034cf7186821712d988d06190e07e respectively) and it's definitely fixed:
```c

void dbg.remove_fighter(void)
{
    undefined4 uVar1;
    int choice;
    
    // void remove_fighter();
    dbg.print_opt((int64_t)"Who do you want to remove from the competition?", 0x50);
    dbg.print_fighters();
    dbg.print_line(0x2d, 0x50);
    sym.imp.printf(data.00401c35);
    _obj.rbuf = 0;
    sym.imp.read(0, obj.rbuf, 4);
    uVar1 = sym.imp.atoi(obj.rbuf);
    // switch table (7 cases) at 0x401d60
    switch(uVar1) {
    case 1:
        if (_obj.MMA_init != 0) {
            _obj.MMA_init = 0;
            sym.imp.free(_obj.MMA_name);
            _obj.num_fighters = _obj.num_fighters + -1;
        }
        break;
    case 2:
        if (_obj.chuck_init != 0) {
            _obj.chuck_init = 0;
            sym.imp.free(_obj.chuck_name);
            _obj.num_fighters = _obj.num_fighters + -1;
        }
        break;
    case 3:
        if (_obj.boxing_init != 0) {
            _obj.boxing_init = 0;
            sym.imp.free(_obj.boxing_name);
            _obj.num_fighters = _obj.num_fighters + -1;
        }
        break;
    case 4:
        if (_obj.smash_init != 0) {
            _obj.smash_init = 0;
            sym.imp.free(_obj.smash_name);
            _obj.num_fighters = _obj.num_fighters + -1;
        }
        break;
    case 5:
        if (_obj.mortal_init != 0) {
            _obj.mortal_init = 0;
            sym.imp.free(_obj.mortal_name);
            _obj.num_fighters = _obj.num_fighters + -1;
        }
        break;
    case 6:
        if (_obj.WWE_init != 0) {
            _obj.WWE_init = 0;
            sym.imp.free(_obj.WWE_name);
            _obj.num_fighters = _obj.num_fighters + -1;
        }
    }
    return;
}
```
