### ISSUE TITLE
Make ghidra-dec use variable name of Rizin and auto refresh after change

### ISSUE THREAD

**Issue by dmknght** [rizinorg/rz-ghidra#43]
By now ghidra-dec is using it default var name
![Screenshot at 2019-09-24 23-06-39](https://user-images.githubusercontent.com/29118926/65529245-fb9f1d80-df1f-11e9-9236-41c2066a34d9.png)
Cutter is using default name of Rizin
![Screenshot at 2019-09-24 23-07-34](https://user-images.githubusercontent.com/29118926/65529334-26897180-df20-11e9-9cc7-6e100a74b7ff.png)
I think ghidra dec should use variable names from Rizin and Cutter so it would be easier for users. (it happens on Rizin as well)
![Screenshot at 2019-09-24 23-08-26](https://user-images.githubusercontent.com/29118926/65529452-56387980-df20-11e9-9039-37361a391562.png)

[KMA.zip](https://github.com/radareorg/r2ghidra-dec/files/3652421/KMA.zip) (Password: 123456)
P/s: I checked with IOLI crackme and they use var names from Rizin so the problem is from these files only :D

**Comment by thestr4ng3r** [comment]
This is already implemented, however in this case it seems it messes up the addresses for some reason. Can you share the binary?

**Comment by dmknght** [comment]
Sure :D Here they are. Password: 123456
[KMA.zip](https://github.com/radareorg/r2ghidra-dec/files/3652421/KMA.zip)
P/s: I checked with IOLI crackme and they use var names from radare2 so the problem is from these files only :D

**Comment by Emi1305** [comment]
I'm having the same problem with every MIPS file I've been using. Unfortunately I can't share those files

What looks a bit weird is that the variable names are correctly replaced in the function declaration but not in the body, attaching screenshots for clarification:

![assembly prolog](https://user-images.githubusercontent.com/9398208/66065089-0e67b280-e51d-11e9-95e7-98f4b0b345b5.png)

![Decompiled](https://user-images.githubusercontent.com/9398208/66065104-14f62a00-e51d-11e9-8202-c36a83392131.png)

Is there any way to communicate directly to the ghidra plugin to manually change it? F.e. through the r2 cli

**Comment by dmknght** [comment]
@Emi1305 maybe you can compile a simple file (like Hello world with variables) and try and send to dev? :D

**Comment by XVilka** [comment]
Could you please retest with the latest `dev`? 7z doesn't recognize the archive format, it seems. I believe, it should be fixed already.

**Comment by dmknght** [comment]
Retested and it was fixed. Thank you :D
