### ISSUE TITLE
Show noreturn information in the function signature

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/rz-ghidra#86]
by @radare
```
[0x100004434]> pdg

void sym.imp.exit(void)
{
    // WARNING: Could not recover jumptable at 0x000100004434. Too many branches
    // WARNING: Treating indirect jump as call
    (*_reloc.exit)();
    return;
}
[0x100004434]>
```

before (void) will be good to have the 'noreturn' attribute

**Comment by radare** [comment]
This “attribute” should be supported by the c compiler, tcc and r2 commands. So maybe a comment .. or a define?

**Comment by thestr4ng3r** [comment]
wat? This is r2ghidra here. It already has the notion of noreturn functions, it just only shows it at callsites, not the signature of a function.

**Comment by radare** [comment]
So... if ghidra can determine this can we import all the analysis intormation into r2 directly?

**Comment by thestr4ng3r** [comment]
I don't know whether the decompiler itself propagates noreturn, we just take the info from r2:
https://github.com/radareorg/r2ghidra-dec/blob/ad48594aaac0ddd17669a2bd9511377ac84e2ba4/src/R2Architecture.cpp#L109-L120

**Comment by fangxlmr** [comment]
@yuuoniy This issue is asigned to you as RSoC micro-task, so you could work on this from now on. Feel free to ask questions and send Pull Requests.

In case for anyone who is not aware about [RSoC](https://keenlab.tencent.com/zh/2021/03/04/RSoC-keenlab-2021/).

CC @XVilka

**Comment by Yuuoniy** [comment]
made a PR #217
