### ISSUE TITLE
Check r2 version in configure

### ISSUE THREAD

**Issue by radare** [rizinorg/rz-ghidra#97]
**Describe the issue**

We need a recent r2 to compile the plugin. So it must be checked at configure or compile time with an #error

**How to reproduce?**
Install an old r2 and try to build r2g

**Expected behavior**

Succesful compilatio 

**Possible fix**

use #if or proper check in the configure

**Comment by thestr4ng3r** [comment]
related: #92

**Comment by XVilka** [comment]
I guess it's not relevant anymore?

**Comment by thestr4ng3r** [comment]
Something similar might become relevant again later, but for now yes.
